### ISSUE TITLE
Error on execute

### ISSUE THREAD

**Issue by JhonnyHRocha** [RafalWilinski/serverless-puppeteer-layers#13]
Hi, i got this error when i execute via get request.
I run npm like Readme and download-latest.sh to update chrome version.
Any one have this error?

2019-07-22T18:04:45.143Z	a497dc1f-1571-4345-9777-1b2065684664	Error: Failed to launch chrome!
[0722/180445.113869:WARNING:resource_bundle.cc(358)] locale_file_path.empty() for locale 
prctl(PR_SET_NO_NEW_PRIVS) failed
[0722/180445.131629:FATAL:zygote_communication_linux.cc(255)] Cannot communicate with zygote
#0 0x5588797be0b9 <unknown>
#1 0x55887972bc63 <unknown>
#2 0x55887973f303 <unknown>
#3 0x55887abe8708 <unknown>
#4 0x55887abeec43 <unknown>
#5 0x5588796f03ac <unknown>
#6 0x55887abef4bc <unknown>
#7 0x5588796e9d41 <unknown>
#8 0x55887972812d <unknown>
#9 0x558879727eab <unknown>
#10 0x7f10776ec445 __libc_start_main
#11 0x558877c6f02a _start

Received signal 6
#0 0x5588797be0b9 <unknown>
#1 0x55887972bc63 <unknown>
#2 0x5588797bdc41 <unknown>
#3 0x7f1078d875e0 <unknown>
#4 0x7f1077700277 __GI_raise
#5 0x7f1077701968 __GI_abort
#6 0x5588797bca85 <unknown>
#7 0x55887973f5e7 <unknown>
#8 0x55887abe8708 <unknown>
#9 0x55887abeec43 <unknown>
#10 0x5588796f03ac <unknown>
#11 0x55887abef4bc <unknown>
#12 0x5588796e9d41 <unknown>
#13 0x55887972812d <unknown>
#14 0x558879727eab <unknown>
#15 0x7f10776ec445 __libc_start_main
#16 0x558877c6f02a _start
r8: 0000000000000000 r9: 0000000000000000 r10: 0000000000000008 r11: 0000000000000202
r12: 00007ffc6f6edf70 r13: 00007ffc6f6ecec8 r14: 00007ffc6f6edf78 r15: 00007ffc6f6edf80
di: 000000000000000b si: 000000000000000b bp: 00007ffc6f6ece70 bx: 00007ffc6f6ecec8
dx: 0000000000000006 ax: 0000000000000000 cx: 00007f1077700277 sp: 00007ffc6f6ecd38
ip: 00007f1077700277 efl: 0000000000000202 cgf: 002b000000000033 erf: 0000000000000000
trp: 0000000000000000 msk: 0000000000000000 cr2: 0000000000000000
[end of stack trace]
Calling _exit(1). Core file will not be generated.

TROUBLESHOOTING: https://github.com/GoogleChrome/puppeteer/blob/master/docs/troubleshooting.md

at onClose (/var/task/node_modules/puppeteer/lib/Launcher.js:340:14)
at Interface.helper.addEventListener (/var/task/node_modules/puppeteer/lib/Launcher.js:329:50)
at emitNone (events.js:111:20)
at Interface.emit (events.js:208:7)
at Interface.close (readline.js:370:8)
at Socket.onend (readline.js:149:10)
at emitNone (events.js:111:20)
at Socket.emit (events.js:208:7)
at endReadableNT (_stream_readable.js:1064:12)
at _combinedTickCallback (internal/process/next_tick.js:138:11)

**Comment by JhonnyHRocha** [comment]
Oh, i resolved it changing args in puppeteer.launch to:

args: ['--no-sandbox', '--disable-setuid-sandbox', '--disable-gpu', '--single-process'],
